### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by konsumer** [archsaber/angular-flatpickr#1]
Please consider publishing on npm. I prefer to use npm to track all dependencies, as opposed to bower for just frontend deps. I can use the github directly, but it'd be better if it was officially tracked by npm.

You can publish with `npm publish`

**Comment by opavader** [comment]
@konsumer My bad, I forgot to do that. Published it just now [npm:angular-flatpickr](https://www.npmjs.com/package/angular-flatpickr)

**Comment by konsumer** [comment]
thanks!
