### ISSUE TITLE
clean up the flatpickr instance on destroy

### ISSUE THREAD

**Issue by s-hoff** [archsaber/angular-flatpickr#11]
Using flatpickr without any extra configuration simply puts it on the body. When e.g. switching between views, the input field (and this directive) it belongs to is destroyed. However, all the extra markup on the body and probably the instance itself remains.
Calling `vp.destroy` in an `element.on('$destroy')` hook should solve this and clean up properly.

**Comment by agaurav** [comment]
Yeah, this should have been there. Thanks @s-hoff.

**Comment by agaurav** [comment]
closing this with https://github.com/archsaber/angular-flatpickr/pull/12
