### ISSUE TITLE
Why did scope->fpOpts  use '&'?

### ISSUE THREAD

**Issue by babycannotsay** [archsaber/angular-flatpickr#15]
I know function is also a object, but why can't set scope->fpOpts to '=' ? It's easier? right?

**Comment by agaurav** [comment]
@babycannotsay Its mainly a trick I used before the oneway bindings (`<`) came in v1.5
Each `=` assignment creates a watcher, which are the main bottlenecks of an angular app.
Although its not that impactful for this directive as its unlikely anyone will have a lot of date pickers in a page.
