### ISSUE TITLE
Arrow key in keyboard cannot trigger ng-change in Time Picker

### ISSUE THREAD

**Issue by babycannotsay** [archsaber/angular-flatpickr#16]
The main code is shown below

    <input type="text" ng-flatpickr="" fp-opts="options" ng-model="number" ng-change="show()" ng-keydown="show()">

    $scope.options = {
        enableTime: true,
        noCalendar: true,

        enableSeconds: false, // disabled by default

        time_24hr: false, // AM/PM time picker is used by default

        // default format
        dateFormat: "H:i",

        // initial values for time. don't use these to preload a date
        defaultHour: 12,
        defaultMinute: 0
    };
    $scope.show = function () {
        console.log($scope.number);
    }

Using arrow key to change input's value even cannot change `$scope.number`.
`ng-keydown` will be triggered only after pressing arrow key and pressing character key.
Can you fix it?Or it's flatpickr's problem.

**Comment by babycannotsay** [comment]
We can set options' property like `onValueUpdate` to set `$scope.number` real time, but I still cannot understand why arrow key can not trigger the events of `ng-change`.

**Comment by agaurav** [comment]
@babycannotsay Can you try this [pen](https://codepen.io/opavader/pen/OgvEOx?editors=1011) and see if it works for you?
Which version of `angular` & `angular-flatpickr`  are you using?

**Comment by agaurav** [comment]
@babycannotsay Actually it might be an issue of `flatpickr` as it prevents the default event from reaching the angular directive as coded here : [src/flatpickr.js#L1218](https://github.com/chmln/flatpickr/blob/1dadfb9f561700183b0b14d6b78457437779c731/src/flatpickr.js#L1218)

I don't know your use-case but I guess what you really want is a event hook from `flatpickr` which will give you the currently focused date whenever a new date is focused in the picker, similar to the `onChange` hook .

**Comment by babycannotsay** [comment]
@agaurav sorry, I forgot to display demo for you. Here is my [use-case](https://codepen.io/giggle/pen/rwdbPK?editors=1111) which changes some code from your pen.

You can try to use arrow key(arrowup and arrowdown) to see what happened.

**Comment by babycannotsay** [comment]
@agaurav 

> Actually it might be an issue of flatpickr as it prevents the default event from reaching the angular directive as coded here : src/flatpickr.js#L1218

I probably understand what you say about this.

**Comment by agaurav** [comment]
I think ng-model is changed only when the input is settled on a value. `flatpickr` has a separate hook `onValueUpdate` for what you want (more here [flatpickr/events](https://chmln.github.io/flatpickr/events/) ).  In the arrow key case a value is probably selected on most non-navigation keys (arrow, tabs etc.), which is why ng-change was getting called on pressing any character key.

Updated [pen](https://codepen.io/opavader/pen/OgverG?editors=1011) for what i think will work for your use-case & showing the difference in `onChange` & `onValueUpdate` .

**Comment by babycannotsay** [comment]
Thanks for your help.
