### ISSUE TITLE
No 2 way binding?

### ISSUE THREAD

**Issue by karthikrock** [archsaber/angular-flatpickr#18]
Whenever I change the scope variable in my code, which is bound to the flatpickr control the flatpickr value does not change. In other words 2 way binding doesnt seem to work on this. That's the only reason anyone would use this angular version instead of the vanilla version, so let me know if I am doing something wrong.

`<input ng-flatpickr fp-opts="dateOpts" ng-model="currentData.callbackDateTime" data-enabletime="true">`

In my controller:

I tried both:

$scope.currentData.callbackDateTime = '2017-09-08 10:30';
and 
$scope.currentData.callbackDateTime = new Date('2017-09-08 10:30');

This does not update the flatpickr.

**Comment by SebSob** [comment]
@karthikrock I have the same issue, have you found any alternative solutions?

**Comment by karthikrock** [comment]
@SebSob I did not with flatpickr, I went with [angular-moment-picker](https://indrimuska.github.io/angular-moment-picker/)

**Comment by 0xpierson** [comment]
I have the same issue

**Comment by sp90** [comment]
Im using the onChange in the options, that is just thrown directly on to flatpickr more info here https://flatpickr.js.org/options/

```javascript
dateOpts = {
  onChange: function(selectedDates, dateStr, instance){
     // Your code here
     // dateStr is the updated value
  }
} 
```

You should avoid 2-way binding in Angular and future versions of angular is not even supporting the feature. This is the same reason angularjs components isn't supporting 2-way binding

**Comment by chris03** [comment]
If you really want two-way binding (for whatever good or bad reasons), you can enable it manually.
Edit the binding config of `ngModel` change `<` to `=`
```
        bindings: {
            ngModel: '=',
            fpOpts: '<',
            fpOnSetup: '&'
        }
```

**Comment by sp90** [comment]
@chris03 great point, but in the end, it's an anti-pattern if you follow the component-based angular design
