### ISSUE TITLE
Doesn't work in ES6

### ISSUE THREAD

**Issue by cruzlutor** [archsaber/angular-flatpickr#22]
Hello, I'm trying to use this directive with ES6 but I'm getting the following error
![image](https://user-images.githubusercontent.com/1368971/41126349-39dd52e0-6a75-11e8-8d4e-cbe74da30d88.png)

here is my code
```
import angular from 'angular';
import 'angular-flatpickr';

angular
    .module('ngBase', [
    'angular-flatpickr'
])
```

We need extra setup for use it on ES6?

**Comment by agaurav** [comment]
@cruzlutor Sorry, I haven't able to learn about how es6 modules needs to be declared and imported (been working mostly in go & python lately).
If you were able to solve this on your own, do let me know and i will patch it up for others as well.

**Comment by sp90** [comment]
@cruzlutor it seems that your angular module is undefined if you read the message it says that 'module' of undefined and your calling `angular.module(...`

**Comment by sp90** [comment]
This issue seems like your not importing angular correctly `Cannot read property 'module' of undefined` and in this case, the "undefined" would be angular

Please make an example and share so we can see what is going wrong 

Gonna close it and mark as "won't fix" until you give a better example 👍
