### ISSUE TITLE
onchange disables form functionality

### ISSUE THREAD

**Issue by kaangoksal** [archsaber/angular-flatpickr#23]
I'm using angular-flatpickr with Anguar 5 and I have discovered that when onChange option is filled, the component stops populating the form variables. 

```javascript
    public startDateOptions: FlatpickrOptions = {
        //defaultDate: new Date(),
        //enableTime: true,
        //dateFormat: "m-d-Y H:i",
        onChange : function(selectedDates, dateStr, instance) {
            console.log("passed in ");
            console.log(selectedDates);
            console.log(dateStr);
            console.log(instance);
        }
    };

   public onApplyClick(){

        console.log("Click");
        console.log(this.form.get('start_date'));

    }
```
If you comment out the on change parameter, the from gets populated again upon value change.

I have two flatpickr components and I would like to limit the available dates of the second one depending on the date that was selected on the first one. I couldn't find any ways to manipulate the flatpickr instance through ts file after initialization either. What is the correct way to interact with the component?  

Thank you for your work.

**Comment by agaurav** [comment]
My best guess is that flatpickr lib prevents the default event from reaching the angular directive if use pass your own `onChange` function. I have not used angular 5 and even angular for a while but may be using something like `ng-change` to do work of `onChange` might work out for what you are trying to achieve.

**Comment by sp90** [comment]
@kaangoksal I'm personally using something similar which is changing the date if another is changing and I'm using the original flatpickr `onChange` function to make the changes

So I wrap each of the angular-flatpickr directives in angular components and put on my own functionality

But to make it work i had to listen to changes from the outer function and using $timeout to wait for next cycle it make it work - note im using angularjs 1.7.2

```javascript
ctrl.$onChanges = function(changes) {
	$timeout(function() {
		if (changes && changes.date) {
			var newDate = changes.date.currentValue;
			var currentDateInstance = ctrl.dateInstance && ctrl.dateInstance.fpItem;

			if (currentDateInstance) {
				currentDateInstance.setDate(newDate)
			}
		}
	}, 0, true);
}
```

Please reopen the issue if this doesn't resolve your problem

**Comment by kaangoksal** [comment]
Thank you guys for replying back, I solved the issue with the following code: 

```javascript
public startDateOptions: FlatpickrOptions = {  
        defaultDate: new Date(),  
        enableTime: true,  
        dateFormat: 'm-d-Y H:i',  
        onChange: function (parent) {  
            return function (selectedDates, dateStr, instance) {  
                parent.form.controls['startDateFormControl'].setValue(selectedDates);  
                parent.endDatePicker.flatpickr.config.minDate = selectedDates[0];  
                parent.endDatePicker.flatpickr.redraw();  
            };  
        }(this)  
    };  
```

This works as expected, however enableTime does not really work and I couldn't figure out any way to disable the datepicker (to select time). I hide it using css. I hope this is a problem on my end. I'll investigate more and create a new issue when I have an example that i can share.

**Comment by sp90** [comment]
@kaangoksal Perfect thanks for the feedback

**Comment by ritesh74** [comment]
instead of onchanges use onValueUpdate it will not affect the form module
