### ISSUE TITLE
[Suggestion] make an optionally component based version

### ISSUE THREAD

**Issue by sp90** [archsaber/angular-flatpickr#25]
@agaurav I was think a angularjs component based version to match future requirements of the angular enviroment, just have the directive one and the component based side by side so people can call the one they need

Please let me know what you think?

**Comment by agaurav** [comment]
Seems like a great idea. 
Component implementation will be much cleaner & easy to debug.

Although a component implementation already exists for v5+ [mattlewis92/angularx-flatpickr](https://github.com/mattlewis92/angularx-flatpickr)

**Comment by sp90** [comment]
@agaurav I was thinking angular 1.5+ support for cleaner support, and then its possible to choose with an updated version

**Comment by opavader** [comment]
@sp90 Oh for 1.5+, yeah that makes sense. 
Let me know if i can be of any help.

**Comment by agaurav** [comment]
@sp90  Oh for 1.5+, yeah that makes sense.
Let me know if i can be of any help.

**Comment by sp90** [comment]
@agaurav we need to decide how we're implementing it because now you cant attach it to an input, so based on the inline options we should change the internal template and then target that element I think it can be done with a simple if inside the component I will make an example and we can discuss the options

**Comment by sp90** [comment]
@agaurav What about ng-transcluding whatever you like to attach it to that way we don't have to replicate the attributes on to the element, that is wanted. then just target the first child of ng-transclude 👍

**Comment by sp90** [comment]
@agauravI made a new branch that is holding the component-based version, it's getting some updates before I do a pull request 💯
