### ISSUE TITLE
need to bind to ng-model

### ISSUE THREAD

**Issue by yeluolei** [archsaber/angular-flatpickr#3]
any idea to bing this to ng-model? I have tried based on your code, but failed..

**Comment by opavader** [comment]
@yeluolei you can set the `onChange` callback of flatpickr object you get with `fp-on-setup` for binding the date string to a model. 
example below binds the date string to `fpVal`

``` html
<input ng-flatpickr fp-on-setup="datePostSetup(fpItem)">
```

``` js
$scope.datePostSetup = function(fpItem) {
    fpItem.set("onChange", function(dateObject, dateString) {
        $scope.fpVal = dateString;
    });
}
```

If you want I can implement the ng-model approach, but that too will be doing so by using this onChange callback. This way it gives people freedom to use it directly or bind to scope or use it on some other callback.

**Comment by hueper** [comment]
Hello @yeluolei, @opavader there is a pr for this: #2

**Comment by opavader** [comment]
@hueper Merged. thanks for implementing this, and also the spell corrections :)

**Comment by yeluolei** [comment]
@hueper thanks~ that's great
