### ISSUE TITLE
It always show Time zone when initilization

### ISSUE THREAD

**Issue by vucuongkg** [archsaber/angular-flatpickr#33]
Hi
I use directive with but It always show time zone when first render.
I used format without time zone.
After choose different value, it shows correctly without time zone

**Comment by sp90** [comment]
It's much easier if you do a screen dump before an after or a codepen or similar where we can reproduce the error

**Comment by vucuongkg** [comment]
Sure.

First render
![Screenshot_74](https://user-images.githubusercontent.com/6039359/58613577-557c3780-82e0-11e9-9b63-71696da06da9.png)

Select another value
![Screenshot_75](https://user-images.githubusercontent.com/6039359/58613579-557c3780-82e0-11e9-9390-67e1562fe1e9.png)

Result
![Screenshot_76](https://user-images.githubusercontent.com/6039359/58613581-557c3780-82e0-11e9-8070-b8fcb2362e7a.png)

Thanks in advance

**Comment by Semkoo** [comment]
Add in the  fp-opts="$ctrl.dateOpts" with  

``` javascript
$ctrl.dateOpts = {
        altInput: true,
        placeholder: "Change date..", // Default: 'Select Date..'
        defaultDate: new Date(), // Today Date
        dateFormat: "Y-m-d", //<-- THIS WILL CONVERT
}
```
