### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by elibolonur** [archsaber/angular-flatpickr#4]
Could you please write a simple example or write integration part step by step? I try to use it in an MVC project but can't really get it work.

**Comment by opavader** [comment]
@onelly Can you give some details on whats not working? Any error ? Did you install flatpickr and included it before angular-flatpickr.
I have made an example app [angular-flatpickr-example](https://github.com/archsaber/angular-flatpickr-example) , showing the very basic use & setup for using this module 
As I don't know anything about the MVC project you are working with, I can't help you much.
