### ISSUE TITLE
add angular validation support

### ISSUE THREAD

**Issue by yeluolei** [archsaber/angular-flatpickr#5]
do you have any idea to add angular validation support to this model?

I am new to angular, and use validation in my project, I tried to add validation support to this, but failed.

**Comment by opavader** [comment]
I am not sure why you will want angular validation support for this. The date value returned by flatpickr will always be a valid date. For other cases where to enforce a certain behaviour, flatpickr can be configured in the controller. e.g. below

To force user to select a value, you can use the `onChange`  [eventAPI](https://chmln.github.io/flatpickr/#eventAPI). Just set a boolean flag in your controller to true on change event and use it in conjunction with your form validation flags.

Min and max date can also be similarly enforced by flatpickr [maxmindate](https://chmln.github.io/flatpickr/#maxmindate) api.
You can even disable a set of dates with the [disable](https://chmln.github.io/flatpickr/#disable) api.

**Comment by yeluolei** [comment]
that's one way to do this, but I have so many date picker in my page, so I do want use it as an validation rule to the this input required. 

anyway, thanks for your advice, it's very useful.

**Comment by opavader** [comment]
You can still use ngModel's `asyncValidators` to make a common directive for your use.
e.g.

``` javascript
function DateVerify($http, $q) {
    return {
        require: 'ngModel',
        link: function(scope, element, attrs, ngModel) {
            ngModel.$asyncValidators.datepickr = function(modelValue, viewValue) {
                // your validation here
                if (valid) {
                    return true;
                }
                return false;
            }
        }
    };
}

angular.module('myApp')
        .directive('dateVerfiy', DateVerfiy);
```

In the form you can use it as ng-messages to show any error 

``` html
<form name="myForm" ng-submit="myForm.$valid" novalidate role="form">
<input name="startDate" date-verify ng-flatpickr fp-opts="startDateOpts" fp-on-setup="datePostSetup" ng-model="startDate">
<span ng-messages="myForm.startDate.$error" ng-if="myForm.$submitted" role="alert">
         <span ng-message="datepickr" align="center">
                   <span class="form-field-errors">invalid date</span>
         </span>
</span>

</form>
```

But it seems counter intuitive as the aim should be to not let a user pick an invalid date from the flatpickr pop-up rather showing an error once he has done it.

**Comment by yeluolei** [comment]
I will try with this way, thank you very much! you are very helpful!
