### ISSUE TITLE
Async defaultDate

### ISSUE THREAD

**Issue by gelevanog** [archsaber/angular-flatpickr#6]
Is there chance to set defaultDate after ajax calling?
I want to display a formatted date, but i don't want to format ng-model itself.

**Comment by opavader** [comment]
You can use the `setDate` API of flatpickr to set the date after the ajax call is received. As for not  formatting `ng-model`, I am not sure what you mean by that. If you want to get the formatted date from flatpickr itself then you can use the `formatDate` method. 

Here's an example controller which does it : https://github.com/archsaber/angular-flatpickr-example/blob/master/app/view2/view2.js

**Comment by gelevanog** [comment]
Thank you! That works.
