### ISSUE TITLE
set options not update flatpickr

### ISSUE THREAD

**Issue by whq731** [archsaber/angular-flatpickr#8]
angular-flatpickr version: 2.0.0
flatpickr version: 2.3.3-1

`
$scope.datePostSetup = function(fpItem) {
    $scope.flatpickr = fpItem;
}
AJAX().then((res) =>{
 blabla...
//e.g.:
$scope.flatpickr.set('allowInput', false); 
// or $scope.flatpickr.config.allowInput = false 
})
`
I want to set minDate and allowInput and clickOpens
but can't update the flatpickr DOM

**Comment by agaurav** [comment]
Sorry I wasn't able to look into this, probably skipped my notification. It seems the flatpickr object is able to modify the data related options but not DOM related ones.
See this pen here https://codepen.io/opavader/pen/jyyLVq?editors=1010

It is able to set minDate options but not others.

I will report this issue to the flatpickr repo.

**Comment by agaurav** [comment]
@whq731 It seems not all options can be changed after initialisation of `flatpickr` object and `allowInput` & `clickOpen` on of them. As a workaround you can use `ng-disable` or change the element directly to prevent any on-click event.
